/**
 * English copy. Must satisfy `Copy` (derived from `typeof vi`), so the compiler
 * flags any missing or extra key. Natural, conversion-oriented English, not a
 * literal translation of the Vietnamese source.
 */
import type { Copy } from './index';

export const en: Copy = {
  common: {
    continue: 'Continue',
    back: 'Back',
    skip: 'Skip',
    retry: 'Try again',
    progress: 'Quiz progress',
    stepCount: (current: number, total: number) => `Question ${current}/${total}`,
  },
  metric: {
    decrement: (label: string) => `Decrease ${label}`,
    increment: (label: string) => `Increase ${label}`,
    rangeError: (label: string, min: number, max: number, unit: string) =>
      `${label} should be between ${min} and ${max} ${unit}.`,
    quickAdjust: (value: string) => `Set to ${value}`,
  },
  landing: {
    eyebrow: '',
    headline: 'Your body, your goal, your plan',
    subheadline:
      'Answer a few questions in about 3 minutes. Nutree turns your body, goal and training into exact calories, macros and a plan you can actually follow.',
    cta: 'Build my plan',
    legal: {
      prefix: 'By continuing, you agree to Nutree’s ',
      terms: 'Terms',
      connector: ' and ',
      privacy: 'Privacy Policy',
      suffix: '.',
      termsUrl: 'https://nutreeai.com/terms',
      privacyUrl: 'https://nutreeai.com/privacy',
    },
    language: 'EN',
    planBadge: 'Plan',
    planTitle: 'Today’s plan',
    planSubtitle: 'Calories, macros and how to spread them across the day',
    planCalories: '1,470',
    planCaloriesUnit: 'cal / day',
    planMacros: [
      { label: 'Protein', value: '132g' },
      { label: 'Carbs', value: '127g' },
      { label: 'Fat', value: '48g' },
    ],
    planMeals: [
      { label: 'Breakfast', calories: 420, note: 'protein-forward' },
      { label: 'Lunch', calories: 560, note: 'steady energy' },
      { label: 'Dinner', calories: 490, note: 'light & easy' },
    ],
    signals: ['TDEE', 'BMI', 'Protein', 'Carbs', 'Fat', 'Meals', 'Weight'],
    bullets: [
      'Clear TDEE and BMI',
      'Macros split into daily targets',
      'Meal ideas that match your macros',
    ],
    proofStats: [
      { value: '3 min', label: 'to your macro targets' },
      { value: 'Free', label: 'to see your first result' },
    ],
    slides: [
      {
        title: 'Macros made for you',
        body: 'Calories, protein, carbs and fat calculated from your height, weight, goal and activity, not a generic number.',
        metric: '4 numbers',
      },
      {
        title: 'Meals that fit the plan',
        body: 'Nutree suggests AI meal ideas around your macros, so choosing what to eat gets faster every day.',
        metric: 'AI meals',
      },
      {
        title: 'Adjusts as you progress',
        body: 'As your weight and habits change, your plan can update to stay locked on your goal.',
        metric: 'Tracking',
      },
    ],
  },
  name_ask: {
    question: 'What should we call you?',
    placeholder: 'Enter your name',
  },
  welcome: {
    headline: 'Hey [name]!',
    body: 'Nutree will use your answers to calculate your calories, macros, and meal ideas — all personalized for your body and goals.',
    imageAlt: 'A person enjoying a healthy meal',
    stats: [
      { value: '3 min', label: 'to complete' },
      { value: '20 questions', label: 'short & simple' },
      { value: 'Free', label: 'to see your results' },
    ],
    cta: 'Let’s start',
  },
  goal: {
    question: 'What’s your main goal?',
    options: [
      { key: 'cut', label: 'Lose fat' },
      { key: 'bulk', label: 'Build muscle' },
      { key: 'recomp', label: 'Get more toned' },
      { key: 'maintain', label: 'Maintain and eat with clarity' },
    ],
  },
  target_weight: {
    question: 'What’s your target weight?',
    label: 'Target weight',
    hint: 'Pick a round number, or type it in if you already have a goal.',
    unit: 'kg',
    unsure: 'I don’t have a number yet',
    currentLabel: 'Current',
    bmiTargetLabel: 'Target BMI',
    bmiAgeHint: 'Needs age-based assessment',
    bmiCategory: {
      underweight: 'Underweight',
      normal: 'Healthy range',
      overweight: 'Overweight',
      obese: 'Above healthy range',
    },
    goalBadge: {
      cut: 'Lose weight',
      bulk: 'Gain weight',
      recomp: 'Improve body shape',
      maintain: 'Maintain weight',
      aligned: 'Fits your goal',
      adjust: 'Goal needs a check',
      bmiAdjust: 'Check target BMI',
      flexible: 'Flexible goal',
      healthyTitle: (value: number) => `A healthy target is about ${value} kg`,
      healthyBody: 'This sits near a healthy BMI range based on your height.',
      alignedBody: 'This weight direction matches the goal you selected.',
      adjustBody: 'For this goal, choose a target in the opposite direction.',
      flexibleBody: 'You can adjust this target around how you want to improve your body composition.',
    },
  },
  challenges: {
    question: 'What’s held you back before?',
    hint: 'Pick up to 2 that fit best.',
    options: [
      { key: 'no_time', label: 'No time' },
      { key: 'no_motivation', label: 'Low motivation' },
      { key: 'dont_know_what_to_eat', label: 'Not sure what to eat' },
      { key: 'cant_stick_to_diet', label: 'Can’t stick to a diet' },
      { key: 'slow_progress', label: 'Progress feels slow' },
      { key: 'cravings', label: 'Snack cravings' },
      { key: 'stress_eating', label: 'Stress eating' },
      { key: 'confusion', label: 'Too much conflicting advice' },
      { key: 'past_failures', label: 'Tried and failed before' },
    ],
  },
  referral_source: {
    question: 'How did you hear about us?',
    options: [
      { key: 'facebook_group', label: 'Facebook', icon: 'facebook' },
      { key: 'youtube', label: 'YouTube', icon: 'youtube' },
      { key: 'instagram', label: 'Instagram', icon: 'instagram' },
      { key: 'tiktok', label: 'TikTok', icon: 'tiktok' },
      { key: 'google_search', label: 'Google', icon: 'google' },
      { key: 'friend_family', label: 'Friends / family', icon: 'people' },
      { key: 'other', label: 'Other', icon: 'spark' },
    ],
  },
  duration: {
    question: 'How long have you been working on this goal?',
    options: [
      { key: 'just_starting', label: 'Just starting' },
      { key: 'few_months', label: 'A few months' },
      { key: 'over_a_year', label: 'Over a year' },
      { key: 'several_years', label: 'Several years' },
    ],
  },
  motivation: {
    question: 'Why start now?',
    options: [
      { key: 'confidence', label: 'Feel more confident' },
      { key: 'energy', label: 'Have more energy' },
      { key: 'health', label: 'Improve my health' },
      { key: 'clothes', label: 'Fit my clothes better' },
      { key: 'training', label: 'See real training results' },
      { key: 'clarity', label: 'Stop guessing' },
    ],
  },
  reflection: {
    template: '[name], your goal is clear and genuinely doable with the right plan.',
    fallbackName: 'friend',
    goalCaption: 'Goal',
    challengeCaption: 'Main blocker',
    durationCaption: 'Time',
    goalFallback: 'Goal',
    challengeFallback: 'A clear plan',
    todayLabel: 'Today',
    chartLabel: 'Your progress trajectory',
    caption: 'With the right plan, progress gets steady instead of all over the place.',
  },
  sex: {
    question: 'What’s your biological sex?',
    options: [
      { key: 'male', label: 'Male' },
      { key: 'female', label: 'Female' },
    ],
  },
  age: {
    question: 'How old are you?',
    label: 'Age',
    hint: 'Nutree is for users aged 12 and over.',
    unit: 'years',
  },
  body_basics: {
    question: 'Tell Nutree your age and sex',
    hint: 'These two details make your energy estimate more accurate.',
  },
  body_metrics: {
    question: 'Your current height and weight',
    hint: 'Use your latest numbers. Scroll or type them in.',
  },
  height: {
    question: 'How tall are you?',
    heightLabel: 'Height',
    heightHint: 'Use your current height.',
    heightUnit: 'cm',
  },
  weight: {
    question: 'What’s your current weight?',
    weightLabel: 'Current weight',
    weightHint: 'Use your most recent weight to calculate TDEE.',
    weightUnit: 'kg',
  },
  body_review: {
    question: 'Quick check of your details',
    hint: 'Confirm so Nutree builds your plan from the right numbers.',
    cta: 'This looks right',
    goalLabel: 'Goal',
    ageLabel: 'Age',
    heightLabel: 'Height',
    weightLabel: 'Weight',
    targetWeightLabel: 'Target weight',
    goalFallback: 'current goal',
    missingValue: 'Not set',
    targetWeightPending: 'Decide later',
  },
  science: {
    eyebrow: 'How Nutree works',
    headline: 'Nutree uses your data to calculate an accurate plan',
    items: [
      {
        title: 'TDEE — Total Daily Energy Expenditure',
        body: 'Based on your height, weight, age, and sex, Nutree estimates how many calories your body burns each day.',
        icon: '⚡',
      },
      {
        title: 'BMI — Body Mass Index',
        body: 'See where you are on the weight spectrum and how much you need to adjust.',
        icon: '📐',
      },
      {
        title: 'Macros — Split your nutrition',
        body: 'Protein, carbs, and fat are allocated based on your goal (lose, build, or maintain) to optimize results.',
        icon: '🎯',
      },
    ],
    slides: [
      {
        title: 'Macros made for you',
        body: 'Calories, protein, carbs and fat are calculated from your body, goal and activity.',
        metric: 'Personal TDEE',
      },
      {
        title: 'Meals that fit the plan',
        body: 'Nutree suggests how to eat around your macros, so you spend less time doing the math.',
        metric: 'Easier eating',
      },
      {
        title: 'Progress can adjust',
        body: 'Your plan is a starting point. As your body changes, your targets can change too.',
        metric: 'Keep tracking',
      },
    ],
    visualLabels: ['Protein', 'Carbs', 'Fat'],
    carouselLabel: 'Nutree science highlights',
    sourcesEyebrow: 'Research basis',
    previousSlide: 'Previous slide',
    nextSlide: 'Next slide',
    goToSlide: (index: number) => `Go to slide ${index + 1}`,
    sourcesTitle: 'What informs the plan',
    sourcesIntro: 'Nutree references public nutrition principles — this is not an endorsement by any of these organizations.',
    sources: [
      { acronym: 'WHO', name: 'World Health Organization', detail: 'Adequacy, balance, diversity and food safety.', href: 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet' },
      { acronym: 'UNICEF', name: 'UNICEF', detail: 'Practical guidance for healthy eating habits.', href: 'https://www.unicef.org/parenting/food-nutrition' },
      { acronym: 'NIH', name: 'National Institutes of Health', detail: 'Evidence-based health education resources.', href: 'https://ods.od.nih.gov/' },
      { acronym: 'EFSA', name: 'European Food Safety Authority', detail: 'Scientific advice on nutrition and food safety.', href: 'https://www.efsa.europa.eu/en/topics/topic/nutrition' },
    ],
    disclaimer: 'Nutree is not a substitute for personal medical advice.',
    cta: 'Continue',
  },
  body_fat: {
    question: 'Estimate your body fat? (optional)',
    hint: 'Not sure? Skip it. We will use a standard formula.',
    label: 'Body fat',
    inputHint: 'Enter your best estimate if you have one.',
    unit: '%',
  },
  training_days: {
    question: 'How many days a week do you train?',
    unit: 'days / week',
  },
  training_duration: {
    question: 'How long is each session?',
    options: [
      { key: '30', label: '~30 min' },
      { key: '45', label: '~45 min' },
      { key: '60', label: '~60 min' },
      { key: '90', label: '90+ min' },
    ],
  },
  experience: {
    question: 'How much training experience do you have?',
    options: [
      { key: 'beginner', label: 'Beginner (< 1 year)' },
      { key: 'intermediate', label: 'Intermediate (1-3 years)' },
      { key: 'advanced', label: 'Advanced (3+ years)' },
    ],
  },
  training_type: {
    question: 'What do you usually train?',
    hint: 'Select all that apply',
    options: [
      { key: 'weights', label: 'Weights' },
      { key: 'cardio', label: 'Cardio' },
      { key: 'yoga', label: 'Yoga' },
      { key: 'running', label: 'Running' },
      { key: 'swimming', label: 'Swimming' },
      { key: 'martial_arts', label: 'Martial arts' },
      { key: 'calisthenics', label: 'Calisthenics' },
      { key: 'pilates', label: 'Pilates' },
      { key: 'hiit', label: 'HIIT' },
      { key: 'cycling', label: 'Cycling' },
      { key: 'dance', label: 'Dance' },
    ],
  },
  activity_level: {
    question: 'How active is your typical day?',
    options: [
      { key: 'desk', label: 'Desk job / mostly sitting' },
      { key: 'on_feet', label: 'On my feet all day' },
      { key: 'physical', label: 'Physical / manual work' },
    ],
  },
  routine: {
    question: 'What does a normal week look like?',
    hint: 'Combine daily activity and training to save a few taps.',
    dailyActivityLabel: 'Daily activity',
    trainingLabel: 'Training',
    minuteUnit: 'min',
  },
  eating_pattern: {
    question: 'When does eating go off-plan most?',
    options: [
      { key: 'morning', label: 'Rushed mornings' },
      { key: 'lunch', label: 'Hard-to-control lunches' },
      { key: 'evening', label: 'Overeating in the evening' },
      { key: 'late_night', label: 'Late-night snacking' },
      { key: 'weekend', label: 'Weekends' },
      { key: 'eating_out', label: 'Eating out' },
    ],
  },
  diet: {
    question: 'Any dietary needs?',
    hint: 'Pick up to 2. “No restrictions” clears the others.',
    options: [
      { key: 'vegan', label: 'Vegan' },
      { key: 'gluten_free', label: 'Gluten-free' },
      { key: 'dairy_free', label: 'Dairy-free' },
      { key: 'nut_free', label: 'Nut allergy' },
      { key: 'egg_free', label: 'Egg allergy' },
      { key: 'shellfish_free', label: 'Shellfish allergy' },
      { key: 'halal', label: 'Halal' },
      { key: 'none', label: 'No restrictions' },
    ],
  },
  careModal: {
    eyebrow: 'Nutree cares about you',
    title: 'Safer food guidance',
    body: 'We’ll use your choices to avoid suggestions that don’t fit your needs in your meal plan.',
    disclaimer: 'Nutree is not a doctor or healthcare professional. If you have a severe allergy or health condition, speak with a qualified professional before changing your diet.',
    cta: 'Got it',
    editCta: 'Review my choices',
  },
  support_style: {
    question: 'How should Nutree support you?',
    options: [
      { key: 'simple', label: 'Simple, just the main target' },
      { key: 'flexible', label: 'Flexible for busy days' },
      { key: 'detailed', label: 'Detailed macros and meals' },
      { key: 'gentle', label: 'Gentle nudges, no pressure' },
    ],
  },
  preview: {
    eyebrow: 'Nutree is ready',
    headline: 'Nutree has enough data to build your personalized plan',
    items: [
      {
        icon: '📊',
        title: 'Calculate TDEE & BMI',
        body: 'From your height, weight, age, and sex.',
      },
      {
        icon: '🎯',
        title: 'Split macros by goal',
        body: 'Protein, carbs, and fat allocated to optimize results.',
      },
      {
        icon: '🍽️',
        title: 'AI meal ideas',
        body: 'Meals suggested to match your calculated macros.',
      },
    ],
    cta: 'View my plan',
  },
  plan_summary: {
    question: 'Nutree has enough to build your plan',
    hint: 'You will see your calories, macros and why the plan fits before you pay.',
    items: [
      'Calculate TDEE from your body and activity',
      'Split macros around your goal',
      'Set up tracking and meal ideas',
    ],
    cta: 'Show my plan',
  },
  tdee_science_promo: {
    section: '04',
    kicker: 'Lifestyle done',
    headline: 'Nutree is turning your answers into a plan',
    body: 'From your height, weight, goal and training, Nutree calculates your energy needs with a science-based formula, not a one-size-fits-all number.',
    proof: ['TDEE', 'BMI', 'Macros'],
  },
  smart_macro_promo: {
    section: '05',
    kicker: 'Next up',
    headline: 'Macros that adjust to how you eat',
    body: 'Protein, carbs and fat are balanced around your goal, weight and training, so you know exactly how to eat today.',
    proof: ['Protein', 'Carbs', 'Fat'],
  },
  smart_meals_promo: {
    section: '06',
    kicker: 'No more guessing',
    headline: 'AI meal ideas that follow your macros',
    body: 'Once your plan is saved, Nutree can suggest meals that match your targets instead of leaving you to do the math.',
    proof: ['Breakfast', 'Lunch', 'Dinner'],
  },
  calculating: {
    text: 'Building your personalized plan',
    orbits: ['TDEE', 'BMI', 'Macros'],
    unit: 'cal per day',
    macroCaption: 'Nutrition split',
    preparing: 'Finishing your plan…',
    ready: 'Your plan is ready!',
    cta: 'View my plan',
    steps: [
      'Reading your body metrics',
      'Calculating maintenance energy',
      'Splitting macros by goal',
      'Packaging your plan',
    ],
    slides: [
      { title: 'You don’t have to do this alone', body: 'Nutree is turning what you shared into a plan that feels possible to start.' },
      { title: 'There is a reason behind the number', body: 'We compare your body, goal and routine before setting a calorie target.' },
      { title: 'Steady beats perfect', body: 'This plan is built to be tracked and adjusted as your body changes.' },
      { title: 'Almost there', body: 'One more moment and you’ll see your first personalized plan.' },
    ],
  },
  tdee_targets: {
    eyebrow: 'Your first plan',
    headline: 'How much to eat today',
    aha: 'A first draft based on the body, goal and routine you just entered.',
    calories: 'Calories per day',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    macroNote: 'Macros pre-split for each day',
    perDayUnit: 'g/day',
    bmiTitle: 'Your BMI',
    bmiCategories: {
      underweight: 'Underweight',
      normal: 'Normal',
      overweight: 'Overweight',
      obese: 'Obese',
    },
    projectionTitle: 'Path to your target weight',
    projectionWeeks: (weeks: number) => `About ${weeks} weeks`,
    sourceTitle: 'Why this plan fits you',
    sourceItems: [
      'Your calorie target comes from your personal TDEE',
      'Macros are split by your goal and weight',
      'It can adjust as your progress changes',
    ],
  },
  care_pause: {
    eyebrow: 'A moment for you',
    headline: 'You don’t need to be perfect to begin',
    body: 'Nutree will use what you shared to create a realistic starting point you can adjust over time.',
    support: 'We’ll be with you one step at a time.',
    cta: 'Build my plan',
  },
  progress: {
    eyebrow: 'Your projected path',
    question: 'Here’s what could happen next',
    hint: 'Based on your goal and the numbers you shared.',
    startLabel: 'Start',
    monthLabel: 'Month 2',
    monthNumber: (month: number) => `Month ${month}`,
    goalLabel: 'Goal',
    chartLabel: 'Projected path from current weight to target weight',
    weeks: (weeks: number) => `About ${weeks} days at a steady pace.`,
    disclaimer: 'Results vary. This is a planning estimate, not a promise of results.',
    noTarget: 'You don’t need to pick a number today.',
    noTargetHint: 'Nutree can still start with a calorie target and habits that fit you.',
    cta: 'Continue',
  },
  result_promising: {
    eyebrow: 'Ready to save your plan',
    headline: 'This plan doesn’t stop at a single number, [name].',
    body: 'Nutree turns today’s goal into a daily loop: eat to your macros, watch your progress, then adjust as your body changes.',
    withNutree: 'With Nutree',
    withNutreeValue: 'Clear progress each week',
    withoutNutree: 'On your own',
    chartLabel: 'Chart comparing progress with Nutree versus on your own',
    nextTitle: 'When you open the Nutree app',
    nextItems: [
      'Get your calorie and macro targets back',
      'Save your app link and plan code',
      'Continue with AI meal ideas in the app',
    ],
    proofTitle: 'Nutree makes 3 things clear',
    proofCards: [
      {
        title: 'Know your daily target',
        body: 'No more piecing calories and macros together from different sources.',
      },
      {
        title: 'Know what to eat',
        body: 'In-app meal ideas follow the macro targets you just calculated.',
      },
      {
        title: 'Know when to adjust',
        body: 'As your weight changes, your plan can update with your progress.',
      },
    ],
    cta: 'Get my plan',
  },
  email: {
    headline: 'Save your plan and get your welcome reward',
    body: 'Enter your email to save your plan and reveal your welcome price.',
    helper: 'We’ll use it to save your plan and prefill secure checkout. After payment is confirmed, we’ll email a secure link to open your plan in Nutree.',
    placeholder: 'you@example.com',
    cta: 'Save my plan',
    devBypass: 'Skip email locally',
    skip: '',
    invalid: 'That email doesn’t look right',
    error: 'Something went wrong. Please try again.',
    readyBadge: 'Your action plan is ready',
    trustTitle: 'A clear plan starts with what you already shared',
    trustBody: 'Save your plan so you can come back anytime. Your email is used only for this Nutree journey.',
    privacyPrefix: 'Private',
    privacyLine: 'Your information stays private and is never sold to third parties.',
    avatars: ['A', 'M', 'L', 'N'],
  },
  welcomeGift: {
    eyebrow: 'Welcome gift',
    headline: 'A welcome reward for your plan',
    subhead: 'Scratch to reveal your new-user price.',
    revealedHeadline: 'Your 50% welcome price is unlocked',
    ticketAria: 'The 50 percent welcome price is unlocked',
    scratchAria: 'Scratch the card to reveal your 50 percent welcome price',
    scratchHint: 'Scratch or tap to reveal',
    revealButton: 'Reveal 50% price',
    ticketLabel: 'WELCOME50',
    discount: '50%',
    ticketValue: '50% OFF',
    priceLine: (amount: string, plan: string) => `${amount} for ${plan}.`,
    cta: 'Claim reward',
    lockedCta: 'Reveal price first',
  },
  paywall: {
    offerReserved: 'welcome offer reserved for:',
    topCta: 'Grab my plan',
    goalIntro: 'With this plan, you can reach',
    headline: 'Your Nutree Premium plan is ready.',
    subhead: 'Unlock calorie targets, macros, and meal guidance calculated from the information you just shared.',
    goalHeadline: (weight: number, date: string) => `${weight} kg by ${date}`,
    goalChartAria: 'Progress chart toward your target weight',
    goalMarker: 'Goal',
    now: 'NOW',
    goalNote: 'Follow the plan and recommendations to move steadily toward your goal.',
    planTitle: 'Grab your Personal Plan',
    offerEnds: (time: string) => `This offer ends in: ${time}`,
    selectPlanAria: 'Choose your plan',
    todayPrice: 'Due today',
    renewal: 'Renewal',
    recommendedTag: 'Most popular',
    discountTag: (percent: number) => `${percent}% OFF`,
    perDay: 'per day',
    appStoreTitle: 'Loved by iOS users',
    appStoreRating: '4.7/5',
    appStoreReviews: '4k+ App Store reviews',
    repeatPlanTitle: 'Grab your Personal Plan',
    guaranteeTitle: '30-day money-back guarantee',
    guaranteeBody: "Follow your plan for 4 weeks. If you still do not see clear progress, we'll refund your purchase.",
    planRecommendation: 'The 12-week plan gives you enough time to build a consistent tracking rhythm.',
    planResearchNote: 'Your WELCOME50 offer is already applied.',
    includesTitle: 'What’s included?',
    personalTitle: 'A plan designed just for you',
    goalLabel: 'Supports your goal:',
    goalCut: 'Sustainable weight loss',
    goalBulk: 'Controlled weight gain',
    goalMaintain: 'Maintain and feel stronger',
    goalRecomp: 'Improve body composition',
    personalizedFor: 'Personalized for:',
    genderMale: 'Men',
    genderFemale: 'Women',
    genderFallback: 'You',
    calorieLabel: 'Optimized for:',
    calorieFallback: 'Preparing your target',
    activityLabel: 'Matched to your activity:',
    activityValue: (days: number) => `${days} days`,
    providerLabel: 'Secure payment with:',
    termsIntro: 'No free trial. You can cancel renewal under the provider terms.',
    benefits: [
      { title: 'Personalized all-in-one plan', body: 'Calories, macros, water, steps, and recipes.' },
      { title: 'Smart meal logging', body: 'Log meals by photo or search.' },
      { title: 'Full nutrition tracking', body: 'Protein, carbs, fat, fiber, and daily totals.' },
      { title: 'Activity-aware guidance', body: 'Workouts and movement included in your plan.' },
      { title: 'Nutree AI Coach', body: 'Clear guidance whenever you need it.' },
    ],
    secure: 'Secure checkout. Entitlement opens only after provider confirmation.',
    cta: () => 'Grab my plan',
    paypalSummary: (amount: string, renewal: string) => `${amount} today and ${renewal} while active`,
    paypalPlaceholder: 'PayPal buttons render here after the backend returns provider configuration.',
    exactPriceSummary: (_standard: string, today: string, renewal: string, planLabel: string) => {
      const cadence = planLabel.replace('-week', ' weeks');
      return `We've applied the discount to your first ${planLabel} plan. You pay ${today} today, then it auto-renews at the full price of ${renewal} every ${cadence} until you cancel. Cancel at least 1 day before renewal in the app's Subscription Page or live chat.`;
    },
    loading: 'Starting checkout...',
    error: 'Couldn’t start checkout. Please try again.',
    paymentError: 'Payment is being checked. You do not need to pay again.',
  },
  checkout: {
    title: 'Checkout',
    close: 'Back to plans',
    orderTitle: 'Order summary',
    plan: 'Plan subscription',
    discount: '50% welcome discount',
    total: 'Due today',
    renewal: 'Next renewal',
    methodTitle: 'Pay with PayPal',
    methodBody: 'You will be securely redirected to PayPal to confirm your subscription.',
    configurationMissing: 'PayPal is not configured for this environment.',
    approvalPending: 'PayPal approved your subscription. We are completing your plan now.',
    paymentError: 'PayPal could not load. Please try again.',
    security: 'PayPal processes your payment securely. Nutree never stores your card details.',
  },
  momoReturn: {
    headline: 'Confirming your payment',
    body: 'We’re waiting for a secure confirmation from the payment provider.',
    paid: 'Payment confirmed. Taking you to the app download...',
    retry: 'Check again',
  },
  success: {
    headline: 'Your plan is unlocked',
    body: 'After your payment is verified, RevenueCat will email a secure link. Open it in Nutree, then sign in with Google or Apple using the same checkout email. No need to retake the quiz.',
  },
};
