/**
 * All Vietnamese copy, keyed by quiz step slug (matches OnboardingScreenId.rcKey
 * in nutree_ai). Structured so adding a locale later = adding a sibling module.
 */
export const vi = {
  common: {
    continue: 'Tiếp tục',
    back: 'Quay lại',
    skip: 'Bỏ qua',
    retry: 'Thử lại',
    progress: 'Tiến độ bài quiz',
    stepCount: (current: number, total: number) => `Câu ${current}/${total}`,
  },
  metric: {
    decrement: (label: string) => `Giảm ${label}`,
    increment: (label: string) => `Tăng ${label}`,
    rangeError: (label: string, min: number, max: number, unit: string) =>
      `${label} cần nằm trong khoảng ${min}-${max} ${unit}.`,
    quickAdjust: (value: string) => `Điều chỉnh ${value}`,
  },
  landing: {
    eyebrow: '',
    headline: 'Kế hoạch ăn uống riêng cho cơ thể và mục tiêu của bạn',
    subheadline:
      'Trả lời vài câu trong 3 phút. Nutree tính calo, macro và lộ trình khớp với cơ thể, mục tiêu và lịch tập của bạn, không phải con số chung chung.',
    cta: 'Xây kế hoạch của tôi',
    legal: {
      prefix: 'Khi tiếp tục, bạn đồng ý với ',
      terms: 'Điều khoản',
      connector: ' và ',
      privacy: 'Chính sách bảo mật',
      suffix: ' của Nutree.',
      termsUrl: 'https://nutreeai.com/terms',
      privacyUrl: 'https://nutreeai.com/privacy',
    },
    language: 'VI',
    planBadge: 'Plan',
    planTitle: 'Kế hoạch hôm nay',
    planSubtitle: 'Calo, macro và nhịp ăn trong ngày',
    planCalories: '1.470',
    planCaloriesUnit: 'calo / ngày',
    planMacros: [
      { label: 'Protein', value: '132g' },
      { label: 'Carbs', value: '127g' },
      { label: 'Chất béo', value: '48g' },
    ],
    planMeals: [
      { label: 'Sáng', calories: 420, note: 'nhiều protein' },
      { label: 'Trưa', calories: 560, note: 'đủ năng lượng' },
      { label: 'Tối', calories: 490, note: 'nhẹ bụng' },
    ],
    signals: ['TDEE', 'BMI', 'Protein', 'Carbs', 'Fat', 'Bữa ăn', 'Cân nặng'],
    bullets: [
      'TDEE và BMI rõ ràng',
      'Macro chia thành mục tiêu mỗi ngày',
      'Gợi ý bữa ăn khớp macro',
    ],
    proofStats: [
      { value: '3 phút', label: 'để có mục tiêu macro' },
      { value: '0đ', label: 'để xem kết quả ban đầu' },
    ],
    slides: [
      {
        title: 'Macro cá nhân hóa',
        body: 'Tính calo, protein, carb và fat dựa trên chiều cao, cân nặng, mục tiêu và mức vận động của bạn.',
        metric: '4 chỉ số',
      },
      {
        title: 'Bữa ăn khớp mục tiêu',
        body: 'Nutree gợi ý bữa ăn AI theo macro đã tính, giúp bạn chọn món nhanh hơn mỗi ngày.',
        metric: 'AI meal',
      },
      {
        title: 'Điều chỉnh theo tiến độ',
        body: 'Khi cân nặng và thói quen thay đổi, kế hoạch có thể được cập nhật để bám sát mục tiêu hơn.',
        metric: 'Theo dõi',
      },
    ],
  },
  name_ask: {
    question: 'Tên bạn là gì?',
    placeholder: 'Nhập tên của bạn',
  },
  welcome: {
    headline: 'Chào [name]!',
    body: 'Nutree sẽ dùng câu trả lời của bạn để tính calo, macro và gợi ý bữa ăn — tất cả được cá nhân hóa cho cơ thể và mục tiêu của bạn.',
    imageAlt: 'Một người đang thưởng thức bữa ăn lành mạnh',
    stats: [
      { value: '3 phút', label: 'để hoàn thành' },
      { value: '20 câu', label: 'ngắn gọn' },
      { value: '0đ', label: 'miễn phí xem kết quả' },
    ],
    cta: 'Bắt đầu ngay',
  },
  goal: {
    question: 'Mục tiêu chính của bạn là gì?',
    options: [
      { key: 'cut', label: 'Giảm cân' },
      { key: 'bulk', label: 'Tăng cơ' },
      { key: 'recomp', label: 'Cải thiện vóc dáng' },
      { key: 'maintain', label: 'Giữ cân và ăn rõ ràng hơn' },
    ],
  },
  target_weight: {
    question: 'Cân nặng mục tiêu của bạn?',
    label: 'Cân nặng mục tiêu',
    hint: 'Chọn số tròn hoặc nhập trực tiếp nếu bạn đã có mục tiêu.',
    unit: 'kg',
    unsure: 'Tôi chưa có con số cụ thể',
    currentLabel: 'Hiện tại',
    bmiTargetLabel: 'BMI mục tiêu',
    bmiAgeHint: 'Cần đánh giá theo độ tuổi',
    bmiCategory: {
      underweight: 'Thiếu cân',
      normal: 'Vùng khỏe mạnh',
      overweight: 'Thừa cân',
      obese: 'Cao hơn vùng khỏe mạnh',
    },
    goalBadge: {
      cut: 'Giảm cân',
      bulk: 'Tăng cân',
      recomp: 'Cải thiện vóc dáng',
      maintain: 'Giữ cân',
      aligned: 'Phù hợp mục tiêu',
      adjust: 'Chưa khớp mục tiêu',
      bmiAdjust: 'Cần xem lại BMI',
      flexible: 'Mục tiêu linh hoạt',
      healthyTitle: (value: number) => `Mục tiêu lành mạnh khoảng ${value} kg`,
      healthyBody: 'Mốc này nằm gần vùng BMI lành mạnh dựa trên chiều cao của bạn.',
      alignedBody: 'Hướng cân nặng này khớp với mục tiêu bạn đã chọn.',
      adjustBody: 'Với mục tiêu hiện tại, hãy chọn một mốc ở hướng ngược lại.',
      flexibleBody: 'Bạn có thể điều chỉnh mốc này theo cách bạn muốn cải thiện vóc dáng.',
    },
  },
  challenges: {
    question: 'Bạn đã gặp khó khăn nào?',
    hint: 'Chọn tối đa 2 mục đúng nhất.',
    options: [
      { key: 'no_time', label: 'Không có thời gian' },
      { key: 'no_motivation', label: 'Thiếu động lực' },
      { key: 'dont_know_what_to_eat', label: 'Không biết ăn gì' },
      { key: 'cant_stick_to_diet', label: 'Không thể duy trì chế độ ăn' },
      { key: 'slow_progress', label: 'Tiến độ chậm' },
      { key: 'cravings', label: 'Thèm ăn vặt' },
      { key: 'stress_eating', label: 'Ăn do stress' },
      { key: 'confusion', label: 'Quá nhiều lời khuyên mâu thuẫn' },
      { key: 'past_failures', label: 'Thất bại trước đây' },
    ],
  },
  referral_source: {
    question: 'Bạn biết đến chúng tôi qua đâu?',
    options: [
      { key: 'facebook_group', label: 'Facebook', icon: 'facebook' },
      { key: 'youtube', label: 'YouTube', icon: 'youtube' },
      { key: 'instagram', label: 'Instagram', icon: 'instagram' },
      { key: 'tiktok', label: 'TikTok', icon: 'tiktok' },
      { key: 'google_search', label: 'Google', icon: 'google' },
      { key: 'friend_family', label: 'Bạn bè / gia đình', icon: 'people' },
      { key: 'other', label: 'Khác', icon: 'spark' },
    ],
  },
  duration: {
    question: 'Bạn đã cố gắng đạt mục tiêu trong bao lâu?',
    options: [
      { key: 'just_starting', label: 'Mới bắt đầu' },
      { key: 'few_months', label: 'Vài tháng' },
      { key: 'over_a_year', label: 'Hơn một năm' },
      { key: 'several_years', label: 'Nhiều năm' },
    ],
  },
  motivation: {
    question: 'Điều gì khiến bạn muốn bắt đầu lúc này?',
    options: [
      { key: 'confidence', label: 'Tự tin hơn với cơ thể' },
      { key: 'energy', label: 'Có nhiều năng lượng hơn' },
      { key: 'health', label: 'Cải thiện sức khỏe' },
      { key: 'clothes', label: 'Mặc đồ vừa và đẹp hơn' },
      { key: 'training', label: 'Tập luyện có kết quả rõ hơn' },
      { key: 'clarity', label: 'Không muốn đoán mò nữa' },
    ],
  },
  reflection: {
    template: '[name], mục tiêu của bạn đã rõ ràng và hoàn toàn khả thi với một kế hoạch đúng.',
    fallbackName: 'Bạn',
    goalCaption: 'Mục tiêu',
    challengeCaption: 'Rào cản chính',
    durationCaption: 'Thời gian',
    goalFallback: 'Mục tiêu',
    challengeFallback: 'Kế hoạch rõ ràng',
    todayLabel: 'Hôm nay',
    chartLabel: 'Lộ trình tiến bộ của bạn',
    caption: 'Với kế hoạch đúng, tiến độ trở nên ổn định thay vì thất thường.',
  },
  sex: {
    question: 'Giới tính sinh học của bạn?',
    options: [
      { key: 'male', label: 'Nam' },
      { key: 'female', label: 'Nữ' },
    ],
  },
  age: {
    question: 'Bạn bao nhiêu tuổi?',
    label: 'Tuổi',
    hint: 'Nutree chỉ hỗ trợ người dùng từ 12 tuổi trở lên.',
    unit: 'tuổi',
  },
  body_basics: {
    question: 'Cho Nutree biết tuổi và giới tính của bạn',
    hint: 'Hai thông tin này giúp ước tính nhu cầu năng lượng chính xác hơn.',
  },
  body_metrics: {
    question: 'Chiều cao và cân nặng hiện tại',
    hint: 'Dùng số đo gần nhất của bạn. Bạn có thể cuộn hoặc nhập trực tiếp.',
  },
  height: {
    question: 'Chiều cao hiện tại của bạn?',
    heightLabel: 'Chiều cao',
    heightHint: 'Dùng chiều cao hiện tại của bạn.',
    heightUnit: 'cm',
  },
  weight: {
    question: 'Cân nặng hiện tại của bạn?',
    weightLabel: 'Cân nặng hiện tại',
    weightHint: 'Dùng cân nặng gần nhất để tính TDEE.',
    weightUnit: 'kg',
  },
  body_review: {
    question: 'Kiểm tra nhanh thông tin cơ thể',
    hint: 'Xác nhận để Nutree tính kế hoạch từ đúng dữ liệu của bạn.',
    cta: 'Thông tin đã đúng',
    goalLabel: 'Mục tiêu',
    ageLabel: 'Tuổi',
    heightLabel: 'Chiều cao',
    weightLabel: 'Cân nặng',
    targetWeightLabel: 'Mục tiêu cân nặng',
    goalFallback: 'mục tiêu hiện tại',
    missingValue: 'Chưa có',
    targetWeightPending: 'Sẽ chọn sau',
  },
  science: {
    eyebrow: 'Cách Nutree hoạt động',
    headline: 'Nutree dùng dữ liệu của bạn để tính kế hoạch chính xác',
    items: [
      {
        title: 'TDEE — Năng lượng tiêu hao',
        body: 'Dựa trên chiều cao, cân nặng, tuổi và giới tính, Nutree ước tính lượng calo cơ thể bạn đốt mỗi ngày.',
        icon: '⚡',
      },
      {
        title: 'BMI — Chỉ số khối cơ thể',
        body: 'Giúp bạn biết mình đang ở vùng cân nặng nào và cần điều chỉnh bao nhiêu.',
        icon: '📐',
      },
      {
        title: 'Macro — Chia dinh dưỡng',
        body: 'Protein, carb và fat được phân bổ theo mục tiêu (giảm cân, tăng cơ, giữ dáng) để tối ưu kết quả.',
        icon: '🎯',
      },
    ],
    slides: [
      {
        title: 'Macro dành riêng cho bạn',
        body: 'Calo, protein, carb và fat được tính từ cơ thể, mục tiêu và mức vận động của bạn.',
        metric: 'TDEE cá nhân',
      },
      {
        title: 'Bữa ăn khớp với mục tiêu',
        body: 'Nutree gợi ý cách ăn theo macro để bạn bớt phải tự tính từng món.',
        metric: 'Ăn dễ hơn',
      },
      {
        title: 'Tiến độ có thể điều chỉnh',
        body: 'Kế hoạch là điểm bắt đầu. Khi cơ thể thay đổi, mục tiêu cũng có thể được cập nhật.',
        metric: 'Theo dõi',
      },
    ],
    visualLabels: ['Protein', 'Carb', 'Chất béo'],
    carouselLabel: 'Điểm nổi bật về khoa học của Nutree',
    sourcesEyebrow: 'Nguồn tham khảo',
    previousSlide: 'Slide trước',
    nextSlide: 'Slide tiếp theo',
    goToSlide: (index: number) => `Đến slide ${index + 1}`,
    sourcesTitle: 'Cơ sở tham khảo',
    sourcesIntro: 'Nutree tham khảo các nguyên tắc dinh dưỡng công khai — không phải sự chứng thực của các tổ chức này.',
    sources: [
      { acronym: 'WHO', name: 'World Health Organization', detail: 'Nguyên tắc ăn đủ, cân bằng, đa dạng và an toàn.', href: 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet' },
      { acronym: 'UNICEF', name: 'UNICEF', detail: 'Hướng dẫn dinh dưỡng và thói quen ăn uống lành mạnh.', href: 'https://www.unicef.org/parenting/food-nutrition' },
      { acronym: 'NIH', name: 'National Institutes of Health', detail: 'Tài liệu giáo dục sức khỏe dựa trên bằng chứng.', href: 'https://ods.od.nih.gov/' },
      { acronym: 'EFSA', name: 'European Food Safety Authority', detail: 'Đánh giá khoa học về dinh dưỡng và an toàn thực phẩm.', href: 'https://www.efsa.europa.eu/en/topics/topic/nutrition' },
    ],
    disclaimer: 'Nutree không thay thế tư vấn y tế cá nhân.',
    cta: 'Tiếp tục',
  },
  body_fat: {
    question: 'Ước tính tỷ lệ mỡ cơ thể? (tùy chọn)',
    hint: 'Nếu không chắc, bạn có thể bỏ qua. Chúng tôi sẽ dùng công thức tiêu chuẩn.',
    label: 'Tỷ lệ mỡ cơ thể',
    inputHint: 'Nhập ước tính gần nhất nếu bạn có số đo.',
    unit: '%',
  },
  training_days: {
    question: 'Bạn tập mấy ngày mỗi tuần?',
    unit: 'ngày/tuần',
  },
  training_duration: {
    question: 'Mỗi buổi tập của bạn kéo dài bao lâu?',
    options: [
      { key: '30', label: '~30 phút' },
      { key: '45', label: '~45 phút' },
      { key: '60', label: '~60 phút' },
      { key: '90', label: '90 phút trở lên' },
    ],
  },
  experience: {
    question: 'Kinh nghiệm tập luyện của bạn?',
    options: [
      { key: 'beginner', label: 'Người mới (< 1 năm)' },
      { key: 'intermediate', label: 'Trung cấp (1-3 năm)' },
      { key: 'advanced', label: 'Nâng cao (3+ năm)' },
    ],
  },
  training_type: {
    question: 'Bạn thường tập loại hình nào?',
    hint: 'Chọn tất cả các mục phù hợp',
    options: [
      { key: 'weights', label: 'Tập tạ' },
      { key: 'cardio', label: 'Cardio' },
      { key: 'yoga', label: 'Yoga' },
      { key: 'running', label: 'Chạy bộ' },
      { key: 'swimming', label: 'Bơi lội' },
      { key: 'martial_arts', label: 'Võ thuật' },
      { key: 'calisthenics', label: 'Calisthenics' },
      { key: 'pilates', label: 'Pilates' },
      { key: 'hiit', label: 'HIIT' },
      { key: 'cycling', label: 'Đạp xe' },
      { key: 'dance', label: 'Nhảy' },
    ],
  },
  activity_level: {
    question: 'Mức độ hoạt động hàng ngày của bạn?',
    options: [
      { key: 'desk', label: 'Văn phòng / ngồi nhiều' },
      { key: 'on_feet', label: 'Đứng / di chuyển cả ngày' },
      { key: 'physical', label: 'Lao động chân tay' },
    ],
  },
  routine: {
    question: 'Một tuần bình thường của bạn trông như thế nào?',
    hint: 'Gộp hoạt động hằng ngày và lịch tập để giảm số lần bấm.',
    dailyActivityLabel: 'Hoạt động hằng ngày',
    trainingLabel: 'Tập luyện',
    minuteUnit: 'phút',
  },
  eating_pattern: {
    question: 'Khoảnh khắc ăn uống nào hay lệch kế hoạch nhất?',
    options: [
      { key: 'morning', label: 'Buổi sáng vội' },
      { key: 'lunch', label: 'Bữa trưa khó kiểm soát' },
      { key: 'evening', label: 'Buổi tối dễ ăn quá tay' },
      { key: 'late_night', label: 'Ăn khuya' },
      { key: 'weekend', label: 'Cuối tuần' },
      { key: 'eating_out', label: 'Ăn ngoài' },
    ],
  },
  diet: {
    question: 'Bạn có yêu cầu dinh dưỡng đặc biệt không?',
    hint: 'Chọn tối đa 2 mục. “Không có yêu cầu” sẽ bỏ chọn các mục khác.',
    options: [
      { key: 'vegan', label: 'Thuần chay' },
      { key: 'gluten_free', label: 'Không gluten' },
      { key: 'dairy_free', label: 'Không sữa' },
      { key: 'nut_free', label: 'Dị ứng hạt' },
      { key: 'egg_free', label: 'Dị ứng trứng' },
      { key: 'shellfish_free', label: 'Dị ứng hải sản có vỏ' },
      { key: 'halal', label: 'Halal' },
      { key: 'none', label: 'Không có yêu cầu' },
    ],
  },
  careModal: {
    eyebrow: 'Nutree quan tâm đến bạn',
    title: 'Gợi ý ăn uống an toàn hơn',
    body: 'Nutree sẽ dùng lựa chọn của bạn để tránh những gợi ý không phù hợp trong kế hoạch ăn uống.',
    disclaimer: 'Nutree không thay thế bác sĩ hoặc chuyên gia y tế. Nếu bạn có dị ứng nghiêm trọng hoặc bệnh nền, hãy hỏi chuyên gia trước khi thay đổi chế độ ăn.',
    cta: 'Tôi đã hiểu',
    editCta: 'Kiểm tra lại lựa chọn',
  },
  support_style: {
    question: 'Bạn muốn Nutree hỗ trợ theo kiểu nào?',
    options: [
      { key: 'simple', label: 'Đơn giản, chỉ cần mục tiêu chính' },
      { key: 'flexible', label: 'Linh hoạt theo ngày bận' },
      { key: 'detailed', label: 'Chi tiết macro và bữa ăn' },
      { key: 'gentle', label: 'Nhắc nhẹ, không áp lực' },
    ],
  },
  preview: {
    eyebrow: 'Nutree đã sẵn sàng',
    headline: 'Nutree đã có đủ dữ liệu để dựng kế hoạch riêng cho bạn',
    items: [
      {
        icon: '📊',
        title: 'Tính TDEE và BMI',
        body: 'Từ chiều cao, cân nặng, tuổi và giới tính của bạn.',
      },
      {
        icon: '🎯',
        title: 'Chia macro theo mục tiêu',
        body: 'Protein, carb, fat được phân bổ để tối ưu kết quả.',
      },
      {
        icon: '🍽️',
        title: 'Gợi ý bữa ăn AI',
        body: 'Bữa ăn được gợi ý khớp với macro đã tính.',
      },
    ],
    cta: 'Xem kế hoạch của tôi',
  },
  plan_summary: {
    question: 'Nutree đã đủ dữ liệu để dựng kế hoạch',
    hint: 'Bạn sẽ thấy calo, macro và lý do kế hoạch phù hợp trước khi thanh toán.',
    items: [
      'Tính TDEE từ cơ thể và mức vận động',
      'Chia macro theo mục tiêu của bạn',
      'Chuẩn bị nhịp theo dõi và gợi ý bữa ăn',
    ],
    cta: 'Xem kế hoạch của tôi',
  },
  tdee_science_promo: {
    section: '04',
    kicker: 'Đã xong phần lối sống',
    headline: 'Nutree đang ghép dữ liệu của bạn thành kế hoạch',
    body: 'Từ chiều cao, cân nặng, mục tiêu và lịch tập, Nutree tính nhu cầu năng lượng bằng công thức khoa học thay vì một con số chung chung.',
    proof: ['TDEE', 'BMI', 'Macro'],
  },
  smart_macro_promo: {
    section: '05',
    kicker: 'Bước tiếp theo',
    headline: 'Macro tự động điều chỉnh theo thói quen ăn uống',
    body: 'Protein, carb và fat được cân bằng theo mục tiêu, cân nặng và lịch tập để bạn biết hôm nay nên ăn thế nào.',
    proof: ['Protein', 'Carb', 'Fat'],
  },
  smart_meals_promo: {
    section: '06',
    kicker: 'Không cần đoán mò',
    headline: 'Gợi ý bữa ăn AI sẽ bám theo macro của bạn',
    body: 'Sau khi lưu kế hoạch, Nutree có thể gợi ý bữa ăn khớp mục tiêu thay vì để bạn tự tính từng món.',
    proof: ['Bữa sáng', 'Bữa trưa', 'Bữa tối'],
  },
  calculating: {
    text: 'Đang tính kế hoạch cho [name]',
    orbits: ['TDEE', 'BMI', 'Macro'],
    unit: 'kcal mỗi ngày',
    macroCaption: 'Phân bổ dinh dưỡng',
    preparing: 'Đang hoàn tất kế hoạch…',
    ready: 'Kế hoạch của bạn đã sẵn sàng!',
    cta: 'Xem kế hoạch của tôi',
    steps: [
      'Đọc chỉ số cơ thể',
      'Tính năng lượng duy trì',
      'Chia macro theo mục tiêu',
      'Gói lại thành kế hoạch',
    ],
    slides: [
      { title: 'Bạn không cần làm điều này một mình', body: 'Nutree đang biến những câu trả lời của bạn thành một kế hoạch dễ bắt đầu.' },
      { title: 'Một con số có lý do phía sau', body: 'Chúng tôi đối chiếu cơ thể, mục tiêu và thói quen trước khi đưa ra mục tiêu calo.' },
      { title: 'Tiến độ ổn định quan trọng hơn hoàn hảo', body: 'Kế hoạch này được thiết kế để bạn có thể theo dõi và điều chỉnh theo thời gian.' },
      { title: 'Sắp xong rồi', body: 'Chỉ còn một bước nữa để xem bản kế hoạch đầu tiên của bạn.' },
    ],
  },
  tdee_targets: {
    eyebrow: 'Kế hoạch đầu tiên',
    headline: 'Hôm nay bạn nên ăn bao nhiêu',
    aha: 'Đây là bản nháp dựa trên cơ thể, mục tiêu và lịch sinh hoạt bạn vừa nhập.',
    calories: 'Calo mỗi ngày',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Chất béo',
    macroNote: 'Macro chia sẵn cho từng ngày',
    perDayUnit: 'g/ngày',
    bmiTitle: 'Chỉ số BMI của bạn',
    bmiCategories: {
      underweight: 'Thiếu cân',
      normal: 'Bình thường',
      overweight: 'Thừa cân',
      obese: 'Béo phì',
    },
    projectionTitle: 'Lộ trình đến cân nặng mục tiêu',
    projectionWeeks: (weeks: number) => `Dự kiến ${weeks} tuần`,
    sourceTitle: 'Vì sao kế hoạch này phù hợp',
    sourceItems: [
      'Mục tiêu calo đến từ TDEE cá nhân',
      'Macro được chia theo mục tiêu và cân nặng',
      'Có thể điều chỉnh khi tiến độ thay đổi',
    ],
  },
  care_pause: {
    eyebrow: 'Một phút cho bạn',
    headline: 'Bạn không cần hoàn hảo để bắt đầu',
    body: 'Nutree sẽ dùng dữ liệu bạn vừa chia sẻ để tạo một điểm bắt đầu vừa sức và có thể điều chỉnh.',
    support: 'Mình sẽ ở đây cùng bạn từng bước.',
    cta: 'Bắt đầu tính kế hoạch',
  },
  progress: {
    eyebrow: 'Lộ trình dự kiến',
    question: 'Điều gì có thể xảy ra tiếp theo',
    hint: 'Dựa trên mục tiêu và chỉ số hiện tại của bạn.',
    startLabel: 'Bắt đầu',
    monthLabel: 'Tháng 2',
    monthNumber: (month: number) => `Tháng ${month}`,
    goalLabel: 'Mục tiêu',
    chartLabel: 'Biểu đồ lộ trình từ cân nặng hiện tại đến mục tiêu',
    weeks: (weeks: number) => `Dự kiến khoảng ${weeks} ngày với nhịp độ ổn định.`,
    disclaimer: 'Kết quả có thể khác nhau. Đây là ước tính để định hướng, không phải lời hứa về kết quả.',
    noTarget: 'Bạn chưa cần chốt một con số hôm nay.',
    noTargetHint: 'Nutree vẫn có thể bắt đầu bằng mục tiêu calo và thói quen phù hợp với bạn.',
    cta: 'Tiếp tục',
  },
  result_promising: {
    eyebrow: 'Sẵn sàng lưu kế hoạch',
    headline: '[name], kế hoạch không dừng ở một con số.',
    body: 'Nutree biến mục tiêu hôm nay thành vòng lặp hằng ngày: ăn đúng macro, xem tiến độ, rồi tự điều chỉnh khi cơ thể thay đổi.',
    withNutree: 'Với Nutree',
    withNutreeValue: 'Tiến độ rõ mỗi tuần',
    withoutNutree: 'Tự theo dõi',
    chartLabel: 'Biểu đồ so sánh tiến độ với Nutree và tự theo dõi',
    nextTitle: 'Khi mở app Nutree',
    nextItems: [
      'Nhận lại mục tiêu calo và macro',
      'Lưu link tải app và mã nhận kế hoạch',
      'Tiếp tục với gợi ý bữa ăn AI trong app',
    ],
    proofTitle: 'Nutree giúp bạn rõ hơn ở 3 điểm',
    proofCards: [
      {
        title: 'Biết mục tiêu mỗi ngày',
        body: 'Không cần tự đoán calo và macro từ nhiều nguồn khác nhau.',
      },
      {
        title: 'Biết nên ăn gì',
        body: 'Gợi ý bữa ăn trong app sẽ bám theo mục tiêu macro đã tính.',
      },
      {
        title: 'Biết khi nào cần chỉnh',
        body: 'Khi cân nặng thay đổi, kế hoạch có thể được cập nhật theo tiến độ.',
      },
    ],
    cta: 'Nhận kế hoạch của tôi',
  },
  email: {
    headline: 'Lưu kế hoạch và nhận quà chào mừng',
    body: 'Nhập email để lưu kế hoạch và mở giá chào mừng.',
    helper: 'Nutree dùng email này để lưu kế hoạch và điền sẵn thanh toán an toàn. Sau khi thanh toán được xác nhận, chúng tôi sẽ gửi link bảo mật để mở kế hoạch trong app.',
    placeholder: 'ban@vidu.com',
    cta: 'Lưu kế hoạch của tôi',
    devBypass: 'Bỏ qua email khi chạy local',
    skip: '',
    invalid: 'Email không hợp lệ',
    error: 'Có lỗi xảy ra. Vui lòng thử lại.',
    readyBadge: 'Kế hoạch hành động của bạn đã sẵn sàng',
    trustTitle: 'Một kế hoạch rõ ràng bắt đầu từ những gì bạn đã chia sẻ',
    trustBody: 'Lưu kế hoạch để có thể quay lại bất cứ lúc nào. Email của bạn chỉ được dùng cho hành trình Nutree này.',
    privacyPrefix: 'Riêng tư',
    privacyLine: 'Thông tin của bạn được giữ riêng tư và không bán cho bên thứ ba.',
    avatars: ['A', 'M', 'L', 'N'],
  },
  welcomeGift: {
    eyebrow: 'Quà chào mừng',
    headline: 'Quà chào mừng cho kế hoạch của bạn',
    subhead: 'Cào để mở mức giá dành cho người dùng mới.',
    revealedHeadline: 'Giảm 50% đã được mở',
    ticketAria: 'Giá chào mừng 50 phần trăm đã mở',
    scratchAria: 'Cào thẻ để mở giá chào mừng 50 phần trăm',
    scratchHint: 'Cào hoặc chạm để mở',
    revealButton: 'Mở giá 50%',
    ticketLabel: 'WELCOME50',
    discount: '50%',
    ticketValue: 'GIẢM 50%',
    priceLine: (amount: string, plan: string) => `${amount} cho gói ${plan}.`,
    cta: 'Claim reward',
    lockedCta: 'Mở giá trước',
  },
  paywall: {
    offerReserved: 'ưu đãi dành riêng cho bạn còn:',
    topCta: 'Chọn gói của tôi',
    goalIntro: 'Với kế hoạch này, bạn có thể đạt',
    headline: 'Kế hoạch Nutree Premium của bạn đã sẵn sàng.',
    subhead: 'Mở khóa mục tiêu calo, macro và hướng dẫn bữa ăn được tính từ dữ liệu bạn vừa cung cấp.',
    goalHeadline: (weight: number, date: string) => `${weight} kg vào ${date}`,
    goalChartAria: 'Biểu đồ tiến trình đến cân nặng mục tiêu',
    goalMarker: 'Mục tiêu',
    now: 'HIỆN TẠI',
    goalNote: 'Theo dõi kế hoạch và các đề xuất để tiến gần hơn đến mục tiêu của bạn.',
    planTitle: 'Chọn kế hoạch cá nhân của bạn',
    offerEnds: (time: string) => `Ưu đãi kết thúc sau: ${time}`,
    selectPlanAria: 'Chọn gói',
    todayPrice: 'Thanh toán hôm nay',
    renewal: 'Gia hạn',
    recommendedTag: 'Phổ biến nhất',
    discountTag: (percent: number) => `Giảm ${percent}%`,
    perDay: 'mỗi ngày',
    appStoreTitle: 'Được người dùng iOS đánh giá cao',
    appStoreRating: '4.7/5',
    appStoreReviews: '4k+ đánh giá App Store',
    repeatPlanTitle: 'Chọn kế hoạch cá nhân của bạn',
    guaranteeTitle: 'Đảm bảo hoàn tiền trong 30 ngày',
    guaranteeBody: 'Nếu bạn làm theo kế hoạch trong 4 tuần và vẫn không thấy tiến triển rõ ràng, chúng tôi sẽ hoàn tiền cho bạn.',
    planRecommendation: 'Gói 12 tuần tạo đủ thời gian để xây dựng nhịp theo dõi đều đặn.',
    planResearchNote: 'Ưu đãi WELCOME50 đã được áp dụng.',
    includesTitle: 'Kế hoạch bao gồm gì?',
    personalTitle: 'Kế hoạch được thiết kế riêng cho bạn',
    goalLabel: 'Hỗ trợ mục tiêu:',
    goalCut: 'Giảm cân bền vững',
    goalBulk: 'Tăng cân có kiểm soát',
    goalMaintain: 'Giữ dáng và khỏe hơn',
    goalRecomp: 'Cải thiện vóc dáng',
    personalizedFor: 'Cá nhân hóa cho:',
    genderMale: 'Nam',
    genderFemale: 'Nữ',
    genderFallback: 'Bạn',
    calorieLabel: 'Tối ưu cho:',
    calorieFallback: 'Đang chuẩn bị',
    activityLabel: 'Khớp với vận động:',
    activityValue: (days: number) => `${days} ngày`,
    providerLabel: 'Thanh toán an toàn qua:',
    termsIntro: 'Không có free trial. Bạn có thể hủy gia hạn theo điều khoản của nhà cung cấp.',
    benefits: [
      { title: 'Kế hoạch tất cả trong một', body: 'Calo, macro, nước, bước chân và gợi ý bữa ăn.' },
      { title: 'Ghi bữa ăn thông minh', body: 'Ghi bữa ăn bằng ảnh hoặc tìm kiếm.' },
      { title: 'Theo dõi dinh dưỡng đầy đủ', body: 'Protein, carb, fat, chất xơ và tổng mỗi ngày.' },
      { title: 'Hướng dẫn theo vận động', body: 'Tính cả lịch tập và vận động trong kế hoạch.' },
      { title: 'Nutree AI Coach', body: 'Hướng dẫn rõ ràng khi bạn cần.' },
    ],
    secure: 'Thanh toán an toàn. Entitlement chỉ mở sau khi nhà cung cấp xác nhận.',
    cta: () => 'Chọn gói của tôi',
    paypalSummary: (amount: string, renewal: string) => `${amount} hôm nay và ${renewal} khi gói còn hoạt động`,
    paypalPlaceholder: 'Nút PayPal sẽ hiển thị tại đây sau khi backend trả cấu hình nhà cung cấp.',
    exactPriceSummary: (_standard: string, today: string, renewal: string, planLabel: string) =>
      `Ưu đãi đã được áp dụng cho gói ${planLabel} đầu tiên. Bạn thanh toán ${today} hôm nay, sau đó gói tự gia hạn theo giá đầy đủ ${renewal} mỗi ${planLabel} cho đến khi bạn hủy. Hủy trước ngày gia hạn ít nhất 1 ngày trong trang Subscription của app hoặc qua live chat.`,
    loading: 'Đang tạo thanh toán...',
    error: 'Không tạo được thanh toán. Vui lòng thử lại.',
    paymentError: 'Thanh toán đang được kiểm tra. Không cần thanh toán lại.',
  },
  checkout: {
    title: 'Thanh toán',
    close: 'Quay lại chọn gói',
    orderTitle: 'Tóm tắt đơn hàng',
    plan: 'Gói đăng ký',
    discount: 'Ưu đãi chào mừng 50%',
    total: 'Thanh toán hôm nay',
    renewal: 'Gia hạn tiếp theo',
    methodTitle: 'Thanh toán bằng PayPal',
    methodBody: 'Bạn sẽ được chuyển đến PayPal để xác nhận gói đăng ký một cách an toàn.',
    configurationMissing: 'PayPal chưa được cấu hình cho môi trường này.',
    approvalPending: 'Đã nhận xác nhận từ PayPal. Chúng tôi đang hoàn tất gói của bạn.',
    paymentError: 'Không thể tải PayPal. Vui lòng thử lại.',
    security: 'Thông tin thanh toán được PayPal xử lý an toàn. Nutree không lưu thông tin thẻ của bạn.',
  },
  momoReturn: {
    headline: 'Đang xác nhận thanh toán',
    body: 'Chúng tôi đang chờ xác nhận thanh toán an toàn từ máy chủ.',
    paid: 'Thanh toán đã xác nhận. Đang chuyển bạn đến bước tải app...',
    retry: 'Kiểm tra lại',
  },
  success: {
    headline: 'Kế hoạch của bạn đã được mở khóa',
    body: 'Sau khi thanh toán được xác minh, RevenueCat sẽ gửi liên kết bảo mật qua email. Mở liên kết trong Nutree, sau đó đăng nhập Google hoặc Apple bằng email đã thanh toán. Bạn không cần làm lại quiz.',
  },
} as const;

export type ViCopy = typeof vi;
